config/routes.rb
Rails.application.routes.draw do
  resources :applicants do
    get :autocomplete_skill_name, :on => :collection
  end

  resources :vacancies do
    get :autocomplete_skill_name, :on => :collection
  end

  root "welcome#index"

end

app/models/applicant.rb
# encoding: utf-8
# == Schema Information
#
# Table name: applicants
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  surname    :string(255)
#  patronymic :string(255)
#  status     :string(255)
#  salary     :integer
#  created_at :datetime
#  updated_at :datetime
#

class Applicant < ActiveRecord::Base
  include Skillable
  has_one :contact, as: :contactable
  accepts_nested_attributes_for :contact

  fio_regexp = /\A[а-яё ]+/i

  def self.statuses
    ['active', 'inactive']
  end

  validates :name, presence: true, format: { with: fio_regexp }
  validates :surname, presence: true, format: { with: fio_regexp }
  validates :patronymic, presence: true, format: { with: fio_regexp }
  validates :status, inclusion: { in: self.statuses, message: "%{value} is not valid" }

  def self.for_vacancy(vacancy_skills)
    query = self
    if vacancy_skills.present?
      query = query.joins(:skills).where("skills.id in (?)", vacancy_skills.pluck(:id))
    end
    query.where("status = ?", "active").order("salary DESC").distinct
  end

  def fullname
    "#{surname} #{name} #{patronymic}"
  end

end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy]
  autocomplete :skill, :name

  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
    @vacancies = Vacancy.for_applicant(@applicant.skills)
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
    @applicant.contact ||= @vacancy.build_contact
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: 'Applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit(:name, :surname, :patronymic, :status, :salary, skills_attributes: [:id, :name], contact_attributes: [:id, :email, :phone])
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/_form.html.haml
= form_for @applicant do |f|
  - if @applicant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@applicant.errors.count, "error")} prohibited this applicant from being saved:"
      %ul
        - @applicant.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :patronymic
    = f.text_field :patronymic
  .field
    = f.label :status
    = select "applicant", 'status', options_for_select(Applicant.statuses)
  .field
    = f.label :salary
    = f.number_field :salary

  = render 'shared/form_contact', f: f

  .actions
    = f.submit 'Save'

  = render 'shared/form_skill', f: f, ob: @applicant

app/views/applicants/edit.html.haml
%h1 Editing applicant

= render 'form'

= link_to 'Show', @applicant
\|
= link_to 'Back', applicants_path

app/views/applicants/index.html.haml
%h1 Listing applicants

%table
  %tr
    %th Name
    %th Surname
    %th Patronymic
    %th Status
    %th Salary
    %th
    %th
    %th

  - @applicants.each do |applicant|
    %tr
      %td= applicant.name
      %td= applicant.surname
      %td= applicant.patronymic
      %td= applicant.status
      %td= applicant.salary
      %td= link_to 'Show', applicant
      %td= link_to 'Edit', edit_applicant_path(applicant)
      %td= link_to 'Destroy', applicant, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Applicant', new_applicant_path

app/views/applicants/new.html.haml
%h1 New applicant

= render 'form'

= link_to 'Back', applicants_path

app/views/applicants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @applicant.name
%p
  %b Surname:
  = @applicant.surname
%p
  %b Patronymic:
  = @applicant.patronymic
%p
  %b Status:
  = @applicant.status
%p
  %b Salary:
  = @applicant.salary

- if @applicant.contact.email.present?
  %p
    %b Email:
    = @applicant.contact.email

- if @applicant.contact.phone.present?
  %p
    %b Phone:
    = @applicant.contact.phone


= link_to 'Edit', edit_applicant_path(@applicant)
\|
= link_to 'Back', applicants_path

%h3
  Навыки

- if @applicant.skills
  - @applicant.skills.each do |skill|
    = skill.name

%h3
  Подходящие вакансии

%p
  - if @vacancies.present?
    - @vacancies.each do |vacancy|
      %li
        = link_to vacancy.name, vacancy_path(vacancy)
        = vacancy.salary