config/routes.rb
Rails.application.routes.draw do
  resources :applicants do
    get :autocomplete_skill_name, :on => :collection
  end

  resources :vacancies do
    get :autocomplete_skill_name, :on => :collection
  end

  root "welcome#index"

end

app/models/vacancy.rb
# == Schema Information
#
# Table name: vacancies
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  validity    :integer
#  salary      :integer
#  created_at  :datetime
#  updated_at  :datetime
#  expire_date :datetime
#

class Vacancy < ActiveRecord::Base
  include Skillable
  has_one :contact, as: :contactable
  accepts_nested_attributes_for :contact

  after_create :set_expire_date

  def self.for_applicant(applicant_skills)
    query = self
    if applicant_skills.present?
      query = query.joins(:skills).where("skills.id in (?)", applicant_skills.pluck(:id))
    end
    query.where("expire_date > ?", Date.today).order("salary ASC").distinct
  end

  private
    def set_expire_date
      validity = self.validity.presence || CONFIG[:default_vacancy_validity]
      expire_date = self.created_at + validity.days
      update_attributes(expire_date: expire_date)
    end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy]
  autocomplete :skill, :name

  # GET /vacancies
  # GET /vacancies.json
  def index
    @vacancies = Vacancy.all
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
    @applicants = Applicant.for_vacancy(@vacancy.skills)
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
    @vacancy.contact ||= @vacancy.build_contact
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)
    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully created.' }
        format.json { render :show, status: :created, location: @vacancy }
      else
        format.html { render :new }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1
  # PATCH/PUT /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacancy }
      else
        format.html { render :edit }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: 'Vacancy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacancy_params
      params.require(:vacancy).permit(:name, :validity, :salary, skills_attributes: [:id, :name], contact_attributes: [:id, :email, :phone])
    end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/vacancies/_form.html.haml
= form_for @vacancy do |f|
  - if @vacancy.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vacancy.errors.count, "error")} prohibited this vacancy from being saved:"
      %ul
        - @vacancy.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :validity
    = f.number_field :validity
  .field
    = f.label :salary
    = f.number_field :salary

  = render 'shared/form_contact', f: f

  .actions
    = f.submit 'Save'

  = render 'shared/form_skill', f: f, ob: @vacancy

app/views/vacancies/edit.html.haml
%h1 Editing vacancy

= render 'form'

= link_to 'Show', @vacancy
\|
= link_to 'Back', vacancies_path

app/views/vacancies/index.html.haml
%h1 Listing vacancies

%table
  %tr
    %th Name
    %th Validity
    %th Salary
    %th
    %th
    %th

  - @vacancies.each do |vacancy|
    %tr
      %td= vacancy.name
      %td= vacancy.validity
      %td= vacancy.salary
      %td= link_to 'Show', vacancy
      %td= link_to 'Edit', edit_vacancy_path(vacancy)
      %td= link_to 'Destroy', vacancy, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Vacancy', new_vacancy_path

app/views/vacancies/new.html.haml
%h1 New vacancy

= render 'form'

= link_to 'Back', vacancies_path

app/views/vacancies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @vacancy.name
%p
  %b Validity:
  = @vacancy.validity
%p
  %b Salary:
  = @vacancy.salary

- if @vacancy.contact.email.present?
  %p
    %b Email:
    = @vacancy.contact.email

- if @vacancy.contact.phone.present?
  %p
    %b Phone:
    = @vacancy.contact.phone

= link_to 'Edit', edit_vacancy_path(@vacancy)
\|
= link_to 'Back', vacancies_path

%h3
  Навыки

- if @vacancy.skills
  - @vacancy.skills.each do |skill|
    = skill.name

%p
  %h3
    Подходящие кандидаты

  - if @applicants.present?
    - @applicants.each do |applicant|
      %li
        = link_to applicant.fullname, applicant_path(applicant)
        = applicant.salary